CREATE TABLE [dbo].[PublicApplicationForm] (
    [Id]                     INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]              NVARCHAR (MAX) NOT NULL,
    [LastName]               NVARCHAR (MAX) NOT NULL,
    [PhoneNumber]            NVARCHAR (MAX) NOT NULL,
    [EmailAddress]           NVARCHAR (MAX) NOT NULL,
    [Address]                NVARCHAR (MAX) NOT NULL,
    [Time]                   NVARCHAR (MAX) NOT NULL,
    [PositionType]           NVARCHAR (MAX) NOT NULL,
    [EmploymentType]         NVARCHAR (MAX) NOT NULL,
    [School]                 NVARCHAR (MAX) NOT NULL,
    [SchoolDepartment]       NVARCHAR (MAX) NOT NULL,
    [Achievements]           NVARCHAR (MAX) NOT NULL,
    [ReferenceOneFullName]   NVARCHAR (MAX) NOT NULL,
    [RelationshipOne]        NVARCHAR (MAX) NOT NULL,
    [ContactInfoOne]         NVARCHAR (MAX) NOT NULL,
    [ReferenceTwoFullName]   NVARCHAR (MAX) NOT NULL,
    [RelationshipTwo]        NVARCHAR (MAX) NOT NULL,
    [ContactInfoTwo]         NVARCHAR (MAX) NOT NULL,
    [ReferenceThreeFullName] NVARCHAR (MAX) NOT NULL,
    [RelationshipThree]      NVARCHAR (MAX) NOT NULL,
    [ContactInfoThree]       NVARCHAR (MAX) NOT NULL,
    [CurriculumVitae]        VARBINARY (MAX) NULL,
    [CreatedTime]            DATETIME2 (7)  NULL,
    [CreatedBy]              NVARCHAR (50)  NULL,
    [UpdatedTime]            DATETIME2 (7)  NULL,
    [UpdatedBy]              NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

